Add DPT 251.600 RGBW
smarthomeNG/plugins pull request #488
Opened 2021-02-22 18:52 UTC by GanfMR

Implemented & Tested for MDT DaliControl Gateway
6 Bytes Object, but only the 4 Bytes are actually used according to docu. 
The first 2 Bytes are filled with '0xff' as default values

2021-02-22 19:24 UTC, GanfMR commented
Oh my second commit was added to this as well, even though I comitted it after my pull request. 
Hue Plugin: BugFix for Groups:
Copy Past Bug Fix. 
Current version does not work correctly for groups, as bri is not set when switching on light.

2021-02-23 10:16 UTC, bmxp requested changes
There should be only one commit per plugin and it is easier for the records if you prepend your commit with ``knx plugin: add DPT 251.600 RGBW``

I'd also recommend to bump up the version numbers in ``plugin.yaml`` and ``__init__.py`` as well.

2021-02-23 12:50 UTC, GanfMR commented
If I understand you correctly:
- I will close this Pull Request
- I will Rollback my Fork
- Have a new commit, to my Fork as proposed
- Create a new Pull Request?

2021-02-23 19:46 UTC, bmxp commented
Yes, this might indeed work. If you think it's too much work I can try to pick your enhancements and merge them into develop.

2021-02-24 08:51 UTC, GanfMR commented
Will do so

2021-02-24 08:51 UTC, closed without merging